<?php
declare(strict_types=1);
require __DIR__.'/../bin/bootstrap.php';require __DIR__.'/../bin/paper/PatternReplay.php';
require __DIR__.'/fixtures/trend_recovery_bars.php';require __DIR__.'/fixtures/prebreak_higher_low_bars.php';
use ChartEntryLab\{CandleClock,ChartPlanEngine};
function prcheck(bool $ok,string $why):void{if(!$ok)throw new RuntimeException($why);echo "PASS $why\n";}
$bars=recovery_bars();$at=end($bars)['available_at'];$original=PaperRrAudit::encode($bars);
$d=PaperPatternReplay::day($bars,'005930.KS',$at,'account1');
prcheck($d['analysis']===(new ChartPlanEngine())->analyze($bars,'005930.KS',$at,'account1',true),'daily engine and profile/context match production');
$future=$bars;$b=end($bars);$b['available_at']+=86400;$b['time']=$b['available_at'];$b['high']=200;$future[]=$b;
prcheck(PaperPatternReplay::day($future,'005930.KS',$at,'account1')===$d,'future bars cannot alter detector input hash, quality or signals');
$bad=$bars;$bad[68]['close']=500;
prcheck(PaperPatternReplay::day($bad,'005930.KS',$at,'account1')['status']==='quality_blocked','invalid prefix is not filtered before day quality check');
$normal=$d['analysis'];$normal['plan']['context_applied']=false;
$blocked=$normal;$blocked['features']['spike_dump_status']='warning';
prcheck(in_array('spike_dump',PaperPatternReplay::blockers($blocked,$normal['plan']['diagnostics']['patterns']['trend_recovery']),true),'independent confirmed pattern still respects common risk');
$plan=['ready'=>true,'signal_at'=>$at,'entry'=>100,'stop'=>90,'target'=>120,'order_valid_bars'=>3];
$futureOnly=[];for($i=1;$i<=22;$i++)$futureOnly[]=['available_at'=>$at+$i*86400,'open'=>101,'high'=>105,'low'=>$i<3?101:99,'close'=>102,'volume'=>1000];
$f=PaperPatternReplay::future($futureOnly,'005930.KS',$at,$at+22*86400);
$t=PaperPatternReplay::trade($plan,$f);
prcheck($t['status']==='closed'&&$t['first_exit']==='time'&&$t['entry_at']===$at+3*86400&&$t['exit_at']===$at+22*86400,'third-session fill has all twenty holding bars');
prcheck(PaperPatternReplay::future($futureOnly,'005930.KS',$at,$at)===[],'future cutoff excludes unavailable sessions');
$corrupt=$futureOnly;$corrupt[2]['low']=500;$f=PaperPatternReplay::future($corrupt,'005930.KS',$at,$at+22*86400);
$h=PaperPatternReplay::horizons(100,$f);
prcheck($h[1]['status']==='complete'&&$h[3]['status']==='quality_blocked','later corrupt candle does not invalidate earlier horizon or disappear');
$t=PaperPatternReplay::trade($plan,$f);prcheck($t['status']==='future_quality_blocked','unresolved trade stops at first invalid future candle');
$terminal=$f;$terminal[0]['open']=80;$terminal[0]['low']=79;
prcheck(PaperPatternReplay::trade($plan,$terminal)['status']==='cancelled_before_entry','invalid later prices do not erase an earlier terminal outcome');
$h=PaperPatternReplay::horizons(100,array_slice($futureOnly,0,2));prcheck($h[3]['status']==='pending'&&!isset($h[3]['return_pct']),'insufficient horizons are pending not zero return');
$dup=$futureOnly;$dup[]=$futureOnly[0];prcheck(PaperPatternReplay::future($dup,'005930.KS',$at,$at+22*86400)[0]===null,'duplicate future sessions blocked');
$pb=prebreak_bars();foreach($pb as &$v)$v['time_kst']=date('Y-m-d H:i:s',$v['time']);unset($v);
$r=PaperPatternReplay::symbol($pb,'005930.KS','test','2026-01-01',end($pb)['available_at'],'account1');
$stages=array_values(array_filter($r['events'],fn($e)=>$e['pattern']==='higher_low'));
prcheck(count($stages)===2&&array_column($stages,'stage')===['watch','breakout'],'repeated watches deduplicated but breakout retained separately');
prcheck($r['duplicates']>=1,'repeated structure actually excluded');
foreach($stages as $e)prcheck($e['trades']===[],'higher-low observation never becomes an order');
$s=PaperPatternReplay::summarize([$r]);$g=$s['groups']['higher_low:breakout:breakout_observed'];
prcheck($g['horizons'][1]['n']===0&&$g['horizons'][1]['pending']===1,'summary excludes pending samples from return denominator');
prcheck(PaperRrAudit::encode($bars)===$original,'source bars untouched');
echo "OK\n";
