<?php
declare(strict_types=1);
require __DIR__.'/../bin/bootstrap.php';
require __DIR__.'/fixtures/trend_recovery_bars.php';
require __DIR__.'/../bin/paper/RrAudit.php';
require __DIR__.'/../bin/paper/SingleConditionReview.php';
require __DIR__.'/../bin/paper/PatternPanel.php';
require __DIR__.'/../bin/paper/StrategyVersion.php';
use ChartEntryLab\{TrendRecovery, ChartPlanEngine, TradeSimulator, PatternEvidence};
function rc(bool $ok, string $why): void { if (!$ok) throw new RuntimeException($why); echo "PASS $why\n"; }
$bars=recovery_bars(); $engine=new TrendRecovery(); $p=$engine->analyze($bars);
rc($p['ready']&&$p['status']==='ready', 'complete recovery is an independent ready setup');
rc($p['entry']===106.0&&$p['stop']===98.0&&$p['target']===130.0&&$p['reward_risk']===3.0, 'fixed confirmation entry, confirmed higher-low stop and nearest target');
rc($p['evidence']['resistance']['index']===53&&$p['evidence']['reference_low']['index']===61&&$p['evidence']['higher_low']['index']===67, 'chronological pivot identities');
rc($p['evidence']['higher_low']['confirmed_at']===$bars[69]['available_at']&&$p['signal_at']===$bars[69]['available_at'], 'signal not backdated to the low');
rc(count(array_filter($p['gates'],fn($v)=>$v===true))===count(TrendRecovery::GATES), 'all required evidence explicit');
foreach(range(59,68) as $i) rc(!$engine->analyze(array_slice($bars,0,$i+1))['ready'], 'no premature signal at prefix '.$i);
$equal=$bars;$equal[64]['close']=100.0;
rc($engine->analyze(array_slice($equal,0,65))['status']==='await_recovery','wick or equal close is not resistance breakout');
$equal=$bars;$equal[67]['low']=90.0;
rc(!$engine->analyze($equal)['ready'],'equal low is not higher low');
$lower=$bars;$lower[67]['low']=88.0;$lower[67]['close']=89.0;
rc($engine->analyze($lower)['status']==='invalidated','close below reference low invalidates after breakout');
$pre=$bars;$pre[64]['close']=99.0;$pre[65]['close']=99.0;$pre[65]['low']=98.0;$pre[66]['close']=99.0;$pre[66]['low']=98.0;$pre[67]['close']=99.0;$pre[68]['close']=99.0;$pre[68]['low']=98.0;
rc(!$engine->analyze($pre)['ready'],'higher low preceding breakout does not complete the pattern');
$pending=$bars;$pending[69]['close']=103.0;
$touch=$pending[69];$touch['available_at']+=86400;$touch['time']=$touch['available_at'];$touch['open']=103.0;$touch['high']=111.0;$touch['low']=98.0;$touch['close']=110.0;
rc(!$engine->analyze([...$pending,$touch])['ready'],'touching an already confirmed higher low requires a new pivot before entry');
$broken=$bars;$broken[40]['close']=131.0;$broken[40]['high']=132.0;
rc($engine->analyze($broken)['target']===132.0,'a previously close-broken overhead pivot is not recycled as target');
$noTarget=recovery_bars(110);
rc($engine->analyze($noTarget)['status']==='no_upper_target','no confirmed upper resistance means no invented target');
$rr=$engine->analyze(recovery_bars(116));
rc(!$rr['ready']&&$rr['status']==='rejected_rr'&&$rr['reward_risk']===1.25,'nearby target fails RR even with a complete pattern');
$future=$bars;$next=end($bars);$next['available_at']+=86400;$next['time']=$next['available_at'];$next['high']=200.0;$future[]=$next;
rc($engine->analyze($future)['status']==='expired','old confirmation never becomes a new recommendation');
$last=$bars[69]['available_at'];$main=new ChartPlanEngine();$a=$main->analyze($bars,'005930.KS',$last,'account1',false);
rc($a['plan']['diagnostics']['patterns']['trend_recovery']===$p,'main path retains complete independent evidence');
rc($a['plan']['pattern']===TrendRecovery::VERSION&&$a['plan']['ready'],'main engine selects a ready recovery when other patterns are not ready');
$proposal=$main->apply([], $a['plan']);
rc($proposal['new_entry']['order_ready']&&$proposal['invalidation_rule']==='confirmed_post_breakout_low','operational projection exposes the recovery plan and correct stop rule');
$universe=ChartEntryLab\PaperScanUniverse::symbols(['rows'=>[['yahoo'=>'005930.KS','entry_recommend'=>$proposal['new_entry']['order_ready']]]]);
rc(isset($universe['005930.KS']),'independent ready pattern reaches operational scan universe');
$riskBars=$bars;$riskBars[48]['high']=125.0;
$risk=$main->analyze($riskBars,'005930.KS',$last,'account1',false);
rc($risk['plan']['diagnostics']['patterns']['trend_recovery']['ready']&&!$risk['plan']['ready']&&$risk['plan']['status']==='risk_blocked','actual top-collapse guard overrides a ready recovery');
$blocked=$main->analyze($bars,'SOXS',$last,'account1',false);
rc(!$blocked['plan']['ready']&&$blocked['plan']['status']==='blocked','profile leverage prohibition remains common');
rc($main->analyze($future,'005930.KS',$last,'account1',false)===$a,'future appended daily bar cannot alter earlier analysis');
// Production guard outcomes must survive an otherwise complete new pattern.
$stale=$main->analyze($bars,'005930.KS',$last+145*3600,'account1',false);
rc(!$stale['plan']['ready']&&$stale['plan']['status']==='stale_data','stale data still blocks the independent pattern');
rc(!TrendRecovery::contextBlocked(['daily'=>'down','weekly'=>'up'],1.5),'daily down alone does not defeat confirmed recovery');
rc(TrendRecovery::contextBlocked(['daily'=>'up','weekly'=>'down'],1.99999)&&!TrendRecovery::contextBlocked(['daily'=>'down','weekly'=>'down'],2.0),'weekly falling threshold strict without display rounding');
$audit=$a;$audit['plan']=array_replace($p,['pattern'=>TrendRecovery::VERSION,'data_asof'=>$last,'asof'=>$last,'context_applied'=>true,
    'context'=>['daily'=>'down','weekly'=>'up'],'diagnostics'=>['patterns'=>['trend_recovery'=>$p]]]);
$audit['features']['spike_dump_status']='none';$audit['features']['top_pattern_status']='none';$audit['decision']['action']='wait';
$rows=PaperRrAudit::evaluate($audit,['can_simulate'=>true]);
rc(!in_array('context_wait',$rows[0]['exclusion_reasons'],true)&&$rows[0]['not_evaluated']===[],'audit respects recovery context and actual gates');
$assessment=PaperSingleConditionReview::assess(['analysis'=>$audit,'quality'=>['can_simulate'=>true]],$rows[0]);
rc($assessment['status']==='ready_reference','saved diagnosis does not reapply old daily-trend prohibition');
$audit['features']['spike_dump_status']='warning';$rows=PaperRrAudit::evaluate($audit,['can_simulate'=>true]);
rc(in_array('spike_dump',$rows[0]['exclusion_reasons'],true),'independent risk blocker still recorded');
$v=PaperPatternView::describe($a['plan']);rc($v['rows'][2]['pattern']==='trend_recovery'&&$v['rows'][2]['known'],'third pattern visible independently');
ob_start();paper_pattern_panel(['basis'=>'completed','plan'=>$a['plan']]);$html=ob_get_clean();
rc(str_contains($html,'추세 이탈 후 회복')&&str_contains($html,'돌파 후 높은 저점'),'human-readable pattern and evidence displayed');
$e=PatternEvidence::capture(['analysis_mode'=>'intraday','completed_trade_plan'=>$a['plan']]);
rc($e['basis']==='completed_reference'&&isset($e['plan']['diagnostics']['patterns']['trend_recovery']),'intraday record remains completed reference, not an intraday order');
$trade=$next;$trade['open']=107.0;$trade['high']=109.0;$trade['low']=105.0;$trade['close']=108.0;
$sim=(new TradeSimulator())->simulate($p,array_merge($bars,[$trade]),20);
rc($sim['filled']&&$sim['entry_at']===$trade['available_at']&&$sim['entry_fill']===106.0,'confirmed recovery uses existing next-bar limit simulation');
rc(in_array('src/TrendRecovery.php',json_decode(file_get_contents(__DIR__.'/../config/paper-strategy-files.json'),true),true),'new operational source belongs to strategy fingerprint');
echo "TREND_RECOVERY_PASS\n";
